### ISSUE TITLE
Update for 0.12 and extract relevant parts into a library?

### ISSUE THREAD

**Issue by Thimoteus** [arthur-xavier/purescript-comonad-ui-todos#1]
I'm interested in using this approach for a project of mine, and it seems like what you've done in this repo has been developed even more from what's in your thesis. Have you thought about extracting the generic parts into a library?

**Comment by arthurxavierx** [comment]
Oh, updating this to 0.12 is a really good call! I'll do that. As for using the technique for applications, it has been developed even further [here](https://github.com/arthurxavierx/purescript-comonad-rss), where you can also find a link to the second part of the thesis. I believe that what's been done there is more likely to be turned into a library, also because it's easier to work with in comparison to the approach used in this repo.

It shouldn't be too laborious a task, and is a project I intend to take soon. Thanks for the interest! :)

**Comment by Thimoteus** [comment]
Awesome! There's also a relevant issue about `CofreeT` here you might be interested in: https://github.com/purescript-contrib/purescript-freet/issues/14

**Comment by arthurxavierx** [comment]
@Thimoteus just FYI, this is still a work in progress but I plan on releasing it on Pursuit this week: https://github.com/arthurxavierx/purescript-comonad-ui.
